apiVersion: v1
kind: ServiceAccount
metadata:
  name: sli-dev-joomla
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: api-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: "Retain"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sli-dev-joomla-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: api-ssd
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdNakNDQlJxZ0F3SUJBZ0lRQTNQK1RLbkxsRWp0anE0aDNwOVJzVEFOQmdrcWhraUc5dzBCQVFzRkFEQmUKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1SMHdHd1lEVlFRREV4UlNZWEJwWkZOVFRDQlNVMEVnUTBFZ01qQXhPREFlCkZ3MHhPREE1TWpRd01EQXdNREJhRncweU1EQTVNak14TWpBd01EQmFNQmt4RnpBVkJnTlZCQU1NRGlvdVpXWmwKYTNScGRpNXphWFJsTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFuaGdrcGxqVQo4USt5ZU4zb0pEYjNLMFR2VjJMMDJtVHN1b0NyaTIydE9XV3p1RjFTdjFzbDNCdFlUbUlZa3VYUi9xMXVTa3BoCnduMGVnNEgwQUExa0hkREVXZVdKTExOemo0dG4vVVJqbktaS3pXSE82WjZtazRYQWFmLzdTcEd3WktiUit5b1AKRUZIcWxIYThWWmpGTkdiL2UvOVFTV2MyZjVkaVBPaGdMTy90RldudUhyZGUveUtPR1ZYWmFyVHNOTE5yQlhvcApidVZScklqbkVXM0lQdzZPdmQ1NjNLdjdVeW54STRiZWZQalUrY3ZJMkpQRUJ0aWY5UHNPdHRSOE16RER6aWdzCnphREsyc0Z2NnVCc0U1SUZndmpVZUlDZ0V2czNtdzBuNG40QnZFdE5vNFpaMEx1M1VlR05yQWs5Q0E5MDFQcTEKVDQwMDJQeVNuZDkwK3dJREFRQUJvNElETHpDQ0F5c3dId1lEVlIwakJCZ3dGb0FVVThvWFdmeHJ3QU1oTHhxdQo1S3FvSElKVzJuVXdIUVlEVlIwT0JCWUVGSGhuWWtYblhONTFRWFpxcGFkTWgxMGVvcjBNTUNjR0ExVWRFUVFnCk1CNkNEaW91WldabGEzUnBkaTV6YVhSbGdneGxabVZyZEdsMkxuTnBkR1V3RGdZRFZSMFBBUUgvQkFRREFnV2cKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQStCZ05WSFI4RU56QTFNRE9nTWFBdgpoaTFvZEhSd09pOHZZMlJ3TG5KaGNHbGtjM05zTG1OdmJTOVNZWEJwWkZOVFRGSlRRVU5CTWpBeE9DNWpjbXd3ClRBWURWUjBnQkVVd1F6QTNCZ2xnaGtnQmh2MXNBUUl3S2pBb0JnZ3JCZ0VGQlFjQ0FSWWNhSFIwY0hNNkx5OTMKZDNjdVpHbG5hV05sY25RdVkyOXRMME5RVXpBSUJnWm5nUXdCQWdFd2RRWUlLd1lCQlFVSEFRRUVhVEJuTUNZRwpDQ3NHQVFVRkJ6QUJoaHBvZEhSd09pOHZjM1JoZEhWekxuSmhjR2xrYzNOc0xtTnZiVEE5QmdnckJnRUZCUWN3CkFvWXhhSFIwY0RvdkwyTmhZMlZ5ZEhNdWNtRndhV1J6YzJ3dVkyOXRMMUpoY0dsa1UxTk1VbE5CUTBFeU1ERTQKTG1OeWREQUpCZ05WSFJNRUFqQUFNSUlCZndZS0t3WUJCQUhXZVFJRUFnU0NBVzhFZ2dGckFXa0FkZ0NrdVFtUQp0QmhZRkllN0U2TE1aM0FLUERXWUJQa2IzN2pqZDgwT3lBM2NFQUFBQVdZSjZwanhBQUFFQXdCSE1FVUNJUUQyCnltWGx5a2p1WlE5ZjFMdFg3a2ZRRTRMdGNyQm11bDJ6eER3bG9iZ0hid0lnUDc5aHNBQjMvMTF3cGszZ0ZveGMKWi9oeDlFU09YYlVETHI1emRybnpuMm9BZHdDSGRiL25XWHo0akVPWlg3M3pidjlXalVkV052OUt0V0RCdE9yLwpYcUNERHdBQUFXWUo2cG5hQUFBRUF3QklNRVlDSVFDYkNuaWEvNFZuQng5QVR5NGJ5ZWVKUDBUekQ5RktxMXVLCmVXUXY5ZnZwL3dJaEFLOUVOQlNEVHRjblUrbjFVQ3NuTzgrNWlkaU5udlFJYmZIclc3MDhPazFNQUhZQXU5bmYKdkIrS2NiV1RsQ09YcXBKN1J6aFhsUXFyVXVnYWtKWmtObzRlMFlVQUFBRm1DZXFaSWdBQUJBTUFSekJGQWlFQQp3SDd4ZjdFUkpFZnlraU5meGo1a2lXb3ovR3duWDhPSXNOcEtZdk9SdmZ3Q0lDRyttVEY0SWZhZkNSYnRkMjZJCmlwZWJKNjMzM1pZdkRVK1BUZ28zT2tCeE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjFuSXdrOHdoSWI2djcKeWtQQXF1c0FnOWxEeWZDWjA1S3VDUXJvTm93QlUzb3NCQ0FSM24vcEl5a0NrRktoYW5UYVFidXV0Zi9CMng2dQo2cERRRW5zVkl4ejU3MXJIek1nc1pZTDU2VGIwamxld1RwcnlqeHQ1RFhyZU5oeC8wdHU0VzloUGY5TVVpeDhYClNZdGw1WGl1STVuWC9mOFFDSUtZTWtyRHZJZ0dRUlAzcjNpdFlNOXE1YzFwQi9JRm1CYWxYUmw3UEluYUtWcHYKVU9WOUxTQUJicVFJT210cUIwd29xWjRGYTlNSGhzQjVTSytaNjlDYXd6OXNiM0V0TW9yN0o2VldQak9iWjZ2cQo2WGxSYUlpclFrWGY5ZEFXOVo2d1Z2bUFUYTk4cUR3TEY0cjg1REdUbTVRS0RIUVNGR3EwaDZJbHowSWoxRWFOClJROWc0SjlYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVzVENDQTVtZ0F3SUJBZ0lRQ0tXaVJzMUxYSXlEMXdLMHU2dFRTVEFOQmdrcWhraUc5dzBCQVFzRkFEQmgKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1TQXdIZ1lEVlFRREV4ZEVhV2RwUTJWeWRDQkhiRzlpWVd3Z1VtOXZkQ0JEClFUQWVGdzB4TnpFeE1EWXhNakl6TXpOYUZ3MHlOekV4TURZeE1qSXpNek5hTUY0eEN6QUpCZ05WQkFZVEFsVlQKTVJVd0V3WURWUVFLRXd4RWFXZHBRMlZ5ZENCSmJtTXhHVEFYQmdOVkJBc1RFSGQzZHk1a2FXZHBZMlZ5ZEM1agpiMjB4SFRBYkJnTlZCQU1URkZKaGNHbGtVMU5NSUZKVFFTQkRRU0F5TURFNE1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTVTMm9paEVvOW5ucGV6b3ppRHR4NFdXTExDbGwvZTB0MUVZZW1FNW4KK01nUDV2aWFITHkrVnBIUCtuZFg1RDE4SU5JdXVBVjh3RnEyNktGNVUwV05JWmlRcDZtTHRJV2pVZVdEUEEyOApPZXloVGxqOVRMazJiZXl0YnRGVTZ5cGJwV1VsdG12WTVWOG5nc3BDN25GUk5DanBmbkRFRDJrUnlKek84eW9LCk1GejRKNEpFOE43TkExdUp3VUVGTVV2SExzMHNjTG9QWmtLY2V3SVJtMVJWMkF4bUZReEprZGY3WU45UGNra2kKZjJYZ20zYjQ4QlpuMHpmMHFYc1NlR3U4NHVhOWd3emp6STd0YlRCamF5VHBUKy9YcFd1QlZ2NmZ2YXJJNmJpawpLQjg1OU9TR1F1dzczWFhnZXVGd0VQSFRJUm9VdGt6dTMvRVErTHR3em5ra2RRSURBUUFCbzRJQlpqQ0NBV0l3CkhRWURWUjBPQkJZRUZGUEtGMW44YThBRElTOGFydVNxcUJ5Q1Z0cDFNQjhHQTFVZEl3UVlNQmFBRkFQZVVEVlcKMFV5N1p2Q2o0aHNidzVleVBkRlZNQTRHQTFVZER3RUIvd1FFQXdJQmhqQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRgpCUWNEQVFZSUt3WUJCUVVIQXdJd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQTBCZ2dyQmdFRkJRY0JBUVFvCk1DWXdKQVlJS3dZQkJRVUhNQUdHR0doMGRIQTZMeTl2WTNOd0xtUnBaMmxqWlhKMExtTnZiVEJDQmdOVkhSOEUKT3pBNU1EZWdOYUF6aGpGb2RIUndPaTh2WTNKc015NWthV2RwWTJWeWRDNWpiMjB2UkdsbmFVTmxjblJIYkc5aQpZV3hTYjI5MFEwRXVZM0pzTUdNR0ExVWRJQVJjTUZvd053WUpZSVpJQVliOWJBRUNNQ293S0FZSUt3WUJCUVVICkFnRVdIR2gwZEhCek9pOHZkM2QzTG1ScFoybGpaWEowTG1OdmJTOURVRk13Q3dZSllJWklBWWI5YkFFQk1BZ0cKQm1lQkRBRUNBVEFJQmdabmdRd0JBZ0l3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUg0angvTEtOVzVaa2xGYwpZV3M4RWpibTBueXpLZVpDMktPVllSN1A4Z2V2S3lzbFdtNFhvNEJTektyMjM1RnNKNGFGdDZ5QWl2MWVZMHRaCi9aTjE4Yk9HU0dTdG9FYy9KRTRvY0l6cjhQNU1nMTFrUllIYm1nWW5yMVJ4ZWtpNW1TZWIzOURHeFRwSkQ0a0cKaHM1bFhOb280Y29uVWlpSndLYXFIN3ZoMmJhcnlkOHBNSVNhZzgzSlVxeVZHYzJ0V1BwTzAzMjkvQ1dxMmtyeQpxdjY2T1NNand1bFV6MGRYZjRPSFFhc1I3Q05mSXIrNEtTY2M2QUJsUTVSREY4NlBHZUU2a2R3U1FrRmlCL2NRCnlzTnlxMGpFRFFUa2ZhMnBqbXVXdE1DTmJCbmhGWEJZZWpmdWJJaGFVYkV2MkZPUUIzZENhditGUGc1ZUV2ZVgKVFZ5TW5Hbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoK
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbmhna3BsalU4USt5ZU4zb0pEYjNLMFR2VjJMMDJtVHN1b0NyaTIydE9XV3p1RjFTCnYxc2wzQnRZVG1JWWt1WFIvcTF1U2twaHduMGVnNEgwQUExa0hkREVXZVdKTExOemo0dG4vVVJqbktaS3pXSE8KNlo2bWs0WEFhZi83U3BHd1pLYlIreW9QRUZIcWxIYThWWmpGTkdiL2UvOVFTV2MyZjVkaVBPaGdMTy90RldudQpIcmRlL3lLT0dWWFphclRzTkxOckJYb3BidVZScklqbkVXM0lQdzZPdmQ1NjNLdjdVeW54STRiZWZQalUrY3ZJCjJKUEVCdGlmOVBzT3R0UjhNekREemlnc3phREsyc0Z2NnVCc0U1SUZndmpVZUlDZ0V2czNtdzBuNG40QnZFdE4KbzRaWjBMdTNVZUdOckFrOUNBOTAxUHExVDQwMDJQeVNuZDkwK3dJREFRQUJBb0lCQUJ6Uk5jMEVvRHdZcW1XUgp2WURzYS8xOUlVdUNoRE5TOWp2QXZJUTd4N21RcWtQTzd3aG1hdTVHSmNDVDdQckozWTlZdWFQZER4ak9pY05hCjZza2ZwOEl2amJyOU5oWHAyQVN3V3BJMTV4cGt6WG5HZkZybFNtUFZtNDgyMCsxeHhQOXowUTdCU2VHbHJPYkgKQmVsc1lYWDkyRkFYNStDWmFidTBNbm43dVp3M0RsdEZXeXhUT2dHQWE1ODdDVWN6Um5BSHFYa0puZFJVUGkwdgpZOHJEeEcrRnNqUk1XVStBdlRndlNMeEFYVk1EVVJYZEJockJoUCtRTGVWZ0JLSmpSTFQxckJUd2VEZEhzdjZmCmZSS2hiZkJ2SW1wSnRhWnN0WHliWG5rNkt2MGozRXdwQ0xPZ1lNaTIyZi8zeURKWTM2S3ZYVUUzbkpYMW1TTWwKWjQwM0M2RUNnWUVBelJqaHk3SmVVUjVSWXlMdXNxbFN0K1Vld1NseGRCQ1cwNlc3bkZZNkd4RHFGREowWmdZQQpFWWM3NHpvaCtzbzZpMHdKZUpGNnY3UWVET0FJS2ZXTEg2Z3VkVUwvbWJNRUVyeTFZQ3NzcWliNG12TzBjUjlVCkQ1VmpHZkJMRFNVT01vS1E2Q0R0eFZoK3pGdk95cHFlK2lhNDRqZ0F1WDhnUVlZeExldlg0YU1DZ1lFQXhWVGYKRmtJSmRQdU5ZZ0JxLzNLNWVWOVowL20yVzFKWTVYVjVld2ZZR2xEYkcra3QzMFJ2Q1lrazJocStwWHJCU1M2WApxMFh5MVpWRHNadDhtZDduazFBR3N2TkxtK1ZBL25GbUI3dEc0ZENMejhOc3JXZ2Yxa2ZVZTFoZVVxVEdPZkgrCjNocExybUJVaEtOUThwaXpIM0hoeUNIZGgzV3dJWGVaWjNmUVJNa0NnWUFWUndLTnpsaG9rL3VmakUwMUxjbk8KR0RBRG5CZ1FFWFNFU29wWElyN3VkZWZDNXFVYXZINmZVdWRNb0loTDYxVDloSXJxL2pTODFLUFZkQnlFdGR1VQpFaStYckxhMXJGTzgyZVQ3TUI5M0c0bnBFV1ZqNHZzbWpybjBRL0NWVVlYU2lhY2MzZVdzOW94WkNTRS85YUNPCmxSdlRKRG8zQkZCRlcvV1lMUUo5ZndLQmdRQ24rNzRGaHFYaVRocG5hUStzOGc3dVFidUlkalZFdkc4c3RycDUKZjQzNXFRYzlWVjFWaVQ0MUVlaXJPc1U4dmFrNUVVN1A0TFgrR0JrT1l0ekphRFllODZzZ1Aza0g5enRDMzJvSgovdVV5YW9QNms5UTZNaitYL0lIbmxxeUZFZndsYTlxWlhDMDgvb2cwZVlyNVdnQnlMbElVT3JBSkZxaWZkTjdFCmMveDU4UUtCZ0FsR0dLOXk3OENxMkc0QnhwTEVUNHppbU5qZ2ZBS2VSNzRIT2xyMDArTlpUa3lob285bmR6Z0sKSFpQNThHRmx5Ty9wRXNwaUZlQjJJNWRDRnJyWGNlZCtRUXdwVGYxSWY1ejVqU291aEt4dG1hRVhxbHg0QXJPbQpJTk5OMmJrRW94VEZjZ2h6K3JQQkZENmhXQXhTVlVqMTBxS0FtY1p3ME94L1haZ2JWL0lMCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: efektiv-wild-site-tls
type: kubernetes.io/tls
---
apiVersion: v1
kind: Service
metadata:
  name: sli-dev-joomla-service
  labels:
    app: sli-dev-joomla
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80     
      protocol: TCP
      name: sli-dev-joomla
  selector:
    app: sli-dev-joomla
---
apiVersion: v1
data:
  GOOGLE_PROJECT_ID: ZWZla3Rpdi1kZXZvcHM=
  GOOGLE_SERVICE_ACCOUNT_JSON_KEY: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZWZla3Rpdi1kZXZvcHMiLAogICJwcml2YXRlX2tleV9pZCI6ICJmMDJiM2M0MTcxNzk4YjZlMmYwYWI0NzhiMmE4ZTczNDJlNzJlM2I4IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUM1RXJNTzNRc0xMcHhUXG51K3YzSU9VM1lPYkIvU0pRaUUybG14ZmFGWUpwczltRlRQRUdGMFFaUm5sNmZrNmtXRnhrUmxmanZhUjVsb3JrXG5FTjdyb2hKYmJLS09yWWtqRG0weCt2b0RkcE8rWkIrRkNLSlN5RDRZNU5XcVA5NUROaXkrOWJ2bHlwZjRMWTI3XG43QkZFcVd2VkNZSWlhd0hDSjdEUjA1VW9kNWM2MGF2SzZET0NzOW5Vc1dRUm01ejlwMFRQckpzMEVOSnhnQ3RHXG5yOWIrVnJrNUtIcGpzTHpkMkVSSGEzN25wRGxtcjNPZkNadElEUWVTL0pzMWxlaWxvWDhZZStuN2xJMGxMcjN0XG5YVkp1K25HSWlhSFZIdzF3VW81YU92Z1hZTm1iQ2kzQ3N0SnFrTE8vYUt1RHNWcEkxY1FFTEhveEJZekFmbWdwXG5kR3U4R0tRdEFnTUJBQUVDZ2dFQU5rV2tDYWRMamtkb1kydTN5ancweTVVWWhtbW5idXRScmM4NTR1T3MzemQxXG5BZENxMjRqbUdPMWdRVW9aNExyaXVTc2hxZkRhY3lkdzZtbUNIYUprOUxkNlFoSGtwY21jdnV2azlqQUhLbTF0XG5DdE9aMm1ITFIveVBKY0pkK09MQm8yd25ZajhUYXAxZE0yOEtMMUxwZ3NzcmhORlJiakM2ZXdXcmQzYitlNm95XG5IcTgyWGJtNHpNbXRjdm85NEFoSVEyZVFVSE5qZ1RWdjR3RTZwdzhsMUNYMWNHVG50SlA1UTRzWCs4Uzd1QS9sXG5FRVRXYVNPLzV0TWpHQ1ZsdE5XU2UrNmxzQ3ZQTjRzVDFrazhsT3A4ei95S3hJSjhDQ1FUZm96K1BiVXh1dkIyXG5TR2o3c1JVOStuWmpZV1RHU3d5Tjh3MWswWkt2aXNkajB1OHJHbktJNXdLQmdRRGUyVXZoWDNIaTdUeHVSckVYXG5RRWw2bnVHeFgzaVFOTldYT3U4M01iaWs3Z1NVeFRxTTlaU1V0cUgwbnJTbzdidjg4NUF0V3dheGxPdkZhNnN4XG40VEQ0MnF1S0JVT3k2VEQ4czFHY2QxMURRaUhVZXFROVM3MnpxNE1VbndlWmQyQW84VzJQMjBiM1hFdGdtQ0FrXG5XTk54MnBhWWtZUFZONGM4dU5JWnN1MzRjd0tCZ1FEVW1zdm9YRWdVQjM0empzYzJOTDRaaUJxcENoTG9admtXXG5pbnRzRUxic2FpYzJiRS9qcmxNU3RiYXRrT3E0OW4wUnZQeEdOZ3VyazE0NHZIMXFIL0RsZlZnbUtyMGFYaXJ1XG56N0dqclJralpqQ3NBVCsvMmFwZzI3SDFBUDI5VXRZTCtPYnpFMDd4Z2EvT2tjL0gvOGhXT3Yya29RTUpsdnJGXG5nZGdneTRmbzN3S0JnUURPczFjQ3NIaitOM1k2QXkvM2xSV1N1eFEwWlkxNmxNY1pBdjBuZ09MM2VCNmZyMkRqXG5wbFl1cWtnR2tiNllnZ3BBVWRxRmQwejZJbHVlUG9RSVBBd2todzlkY2d5ZFFsYkJ6Y0lCRTJaYUlGa29zS2p1XG5nZlp2Vk1LOHVkVmVyNjl0eXFJSk1TYmVBYW1ZNndIRk5PN0xTQ2t2VXFtcGQxdmxJcmtlUlMwZHFRS0JnQTRqXG5OUWdBaXZKNkJSUmNuRGFvanpPWGIxNXFReE9kTlZjZ1lsQ3ZVOXFvdkc3TUNRdjAzYVZTM0JEeW9Ba29xdXh4XG5DcjJJZm9Jc1RJbXRUeEd0aWhGWW9uSDNTWmZsUnltV09oUE9RT3V2c2ZEZUxHVVBqbHJlZ1JqdnRlL1BBRmpQXG5kbHdYbnBwRXEzSXJGQXdTb0RuTHRtNHFIcytXY0pxTnBkZVljVE0xQW9HQkFJZHdzNGk5Z09qZXRkRUFjVTlEXG5OUWV1Vk1oaHUzdmZqM0xFR056S01wUzI3UmpNbmlramR5aU1lVm5UOC8yMWJrUUpDcGZGaGVqcjd5aXdUUjFTXG5ZUW40SU1wejd2ZWZXN0dmK1hqSE1ldUhONDlDUzFaN2JCc1RTK0NUc2FCVThxbDlOWFNKR2NoeVdIQ2svRjVYXG42bjBGRU9wb1AwOUYycndJa3ZybVFmVCtcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICI2NDYyNTA1NzM0MjgtY29tcHV0ZUBkZXZlbG9wZXIuZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDc0NjkwNzQ0MzA0OTU0NTQ2MDAiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5LzY0NjI1MDU3MzQyOC1jb21wdXRlJTQwZGV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0KCg==
  RESTIC_PASSWORD: eVokNTc0cSNWXkBZ
kind: Secret
metadata:
  name: gcs-secret
  namespace: default
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: sli-dev-joomla-ingress
spec:
  rules:
  - host: sli-dev.efektiv.site
    http:
      paths:
      - backend:
          serviceName: sli-dev-joomla-service
          servicePort: 80
        path: /
  tls:
  - hosts:
    - '*.efektiv.site'
    secretName: efektiv-wild-site-tls
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: sli-dev-joomla
  name: sli-dev-joomla-workload
  namespace: default
spec:
  serviceName: sli-dev-joomla-service
  replicas: 1
  selector:
    matchLabels:
      app: sli-dev-joomla
  template:
    metadata:
      labels:
        app: sli-dev-joomla
    spec:
      containers:
      - name: sli-dev-joomla
        image: us.gcr.io/efektiv-devops/sli-dev-joomla:0.0.1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File 
        volumeMounts:
        - mountPath: /bitnami/joomla
          name: sli-dev-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: sli-dev-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: api-ssd
    status:
      phase: Pending
