apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: lamp
  name: lamp
  namespace: default
spec:
  selector:
    matchLabels:
      name: lamp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: lamp
    spec:
      containers:
      - image: us.gcr.io/crowncodes/git-sync-sidecar-organizr:1.0.0
        imagePullPolicy: IfNotPresent
        name: git-sync
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/git
          name: gitsrc
      - image: us.gcr.io/crowncodes/lamp-stack:1.0.0
        imagePullPolicy: IfNotPresent
        name: lamp-stack
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File   
        volumeMounts:
        - mountPath: /var/www/html
          name: gitsrc
      dnsPolicy: ClusterFirst      
      volumes:
      - emptyDir: {}
        name: gitsrc
